# Generated by Django 4.0.3 on 2022-04-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamburguesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrehamburguesa', models.CharField(max_length=45, verbose_name='nombrehamburguesa')),
                ('tipopan', models.CharField(max_length=45, verbose_name='tipopan')),
                ('tipocarne', models.CharField(max_length=45, verbose_name='tipocarne')),
                ('cantidadmedallones', models.IntegerField()),
                ('aderezo', models.CharField(max_length=45, verbose_name='aderezo')),
                ('salsaMrBlack', models.BooleanField()),
                ('fechacreacion', models.DateField(verbose_name='fechacreacion')),
            ],
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrelocal', models.CharField(max_length=45, verbose_name='nombrelocal')),
                ('ciudad', models.CharField(max_length=45, verbose_name='ciudad')),
                ('provincia', models.CharField(max_length=45, verbose_name='provincia')),
                ('direccion', models.CharField(max_length=45, verbose_name='direccion')),
                ('altura', models.IntegerField()),
                ('fechaapertura', models.DateField(verbose_name='fechaapertura')),
            ],
        ),
    ]
