# Generated by Django 4.0.3 on 2022-04-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMrBlack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panchos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepancho', models.CharField(max_length=45, verbose_name='nombrepancho')),
                ('tamaño', models.CharField(max_length=45, verbose_name='tipopan')),
                ('aderezo', models.CharField(max_length=45, verbose_name='aderezo')),
                ('salsa', models.CharField(max_length=45, verbose_name='salsa')),
                ('fechacreacion', models.DateField(verbose_name='fechacreacion')),
            ],
        ),
    ]
