# Generated by Django 4.0.3 on 2022-04-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMrBlack', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesas',
            name='imagen_referencial',
            field=models.ImageField(max_length=255, null=True, upload_to='imagenes/', verbose_name='imagen_referencial'),
        ),
    ]
