# Generated by Django 4.0.3 on 2022-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMrBlack', '0005_hamburguesas_imagen_referencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
        ),
        migrations.DeleteModel(
            name='Panchos',
        ),
    ]
